# Generated by Django 3.2 on 2021-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Teacher',
            field=models.CharField(default='Sir zain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(default='CS@IT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_Available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
