# Generated by Django 3.2.3 on 2021-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
