# Generated by Django 3.2.3 on 2021-07-05 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210705_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='semester',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
