# Generated by Django 3.2.3 on 2021-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='semester',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], null=True),
        ),
    ]
